### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by hakunin** [jhartikainen/dompath#1]
Hi, thanks for this cool library, just what I need.

Would you care to add a licence?

Btw you were mentioned here: https://github.com/fczbkk/css-selector-generator-benchmark#jhartikainen-dompath

**Comment by jhartikainen** [comment]
Fixed with https://github.com/jhartikainen/dompath/commit/d50b86ddc8a8021a7d1a2c80f71140a9a8b94e2f :)
